
server:
  port: 8083
  
spring:
  application:
    name: retail-account
    baseUrl: http://gateway:8080
  redis:
    host: javatesting-redis
    port: 6379
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl