
server:
  port: 8080
  
spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: AuthenUserFilter
        - name: ModifyHeaderFilter
        