
server:
  port: 8081
  
spring:
  application:
    name: pre-deposited-account
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl