
server:
  port: 8081
  
spring:
  application:
    name: pre-deposited-account
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl